title: How to Setup Selenium with ChromeDriver on Ubuntu 18.04 & 16.04
author: Rajeev Singh
email: rajeevsingh303@gmail.com
description: This tutorial will help you to setup Selenium with ChromeDriver on Ubuntu.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
